/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import DAO.DAOArticle;
import Entidad.Article;
import Utils.BoxUtils;
import Utils.PanelUtils;
import Utils.TableUtils;
import java.util.List;

/**
 *
 * @author leons
 */
public class ArticlePanel extends javax.swing.JPanel {

    /**
     * Creates new form ArticlePanel
     */
    public NewArticlePanel newArticle;
    public ViewArticles viewArticles ;
    public EditArticlePanel editArticle;
    private DAOArticle daoT = new DAOArticle();
    List<Article> list = daoT.findAll(); 
    
    public ArticlePanel() {
        initComponents();
        newArticle = new NewArticlePanel();
        viewArticles = new ViewArticles();
        editArticle = new EditArticlePanel();  
        
        PanelUtils.change(addArticleTab, newArticle);
        
        tabs.addChangeListener(e -> {
            switch (tabs.getSelectedIndex()) {
                case 0:
                    PanelUtils.change(addArticleTab, newArticle);
                     TableUtils.fillTableArticle(newArticle.getSchemaClothes(), daoT.findAll()); 
                    break;
                case 1:
                    PanelUtils.change(viewArticlesTab, viewArticles);
                    TableUtils.fillTableArticle(viewArticles.getSchemaClothes(), daoT.findAll());
                    break;
                default:
                    PanelUtils.change(editArticleTab, editArticle);
                    TableUtils.fillTableArticle(editArticle.getSchemaClothes(), daoT.findAll());
                    break;
            }
        });

                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        addArticleTab = new javax.swing.JPanel();
        viewArticlesTab = new javax.swing.JPanel();
        editArticleTab = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(860, 500));
        setLayout(new java.awt.BorderLayout());

        tabs.setPreferredSize(new java.awt.Dimension(800, 300));
        tabs.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabsAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        addArticleTab.setLayout(new java.awt.BorderLayout());
        tabs.addTab("Agregar nuevo artículo", addArticleTab);

        viewArticlesTab.setLayout(new java.awt.BorderLayout());
        tabs.addTab("Ver artículos", viewArticlesTab);

        editArticleTab.setLayout(new java.awt.BorderLayout());
        tabs.addTab("Editar artículo", editArticleTab);

        add(tabs, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void AddBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBActionPerformed
             
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBActionPerformed

    private void AccountBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountBActionPerformed
        
                                              // TODO add your handling code here:
    }//GEN-LAST:event_AccountBActionPerformed

    private void ViewSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewSBActionPerformed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewSBActionPerformed

    private void EditSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditSBActionPerformed
      //TODO add your handling code here:
    }//GEN-LAST:event_EditSBActionPerformed

    private void tabsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabsAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabsAncestorAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addArticleTab;
    private javax.swing.JPanel editArticleTab;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JPanel viewArticlesTab;
    // End of variables declaration//GEN-END:variables
}
