/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import java.awt.BorderLayout;



/**
 *
 * @author leoleguizamon
 */
public class Article extends javax.swing.JPanel {
    
    /**
     * Creates new form Article
     */
    public Article() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        genderDialog = new javax.swing.JDialog();
        acceptNewGenderButtonDialog = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        newGenderLabelDialog = new javax.swing.JLabel();
        newGenderTFDialog = new javax.swing.JTextField();
        editArticlePanel = new javax.swing.JPanel();
        chekboxPanelEdit = new javax.swing.JPanel();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        availableCEdit = new javax.swing.JCheckBox();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        WashCEdit = new javax.swing.JCheckBox();
        IronCEdit = new javax.swing.JCheckBox();
        WaiCEdit = new javax.swing.JCheckBox();
        foldCEdit = new javax.swing.JCheckBox();
        centerLeftPanelEdit = new javax.swing.JPanel();
        GenderL1 = new javax.swing.JLabel();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        GenderBoxEdit = new javax.swing.JComboBox<>();
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        AvalL1 = new javax.swing.JLabel();
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        NameL1 = new javax.swing.JLabel();
        NameTFEdit = new javax.swing.JTextField();
        LaundryL1 = new javax.swing.JLabel();
        WashTFEdit = new javax.swing.JTextField();
        IronL1 = new javax.swing.JLabel();
        IronTFEdit = new javax.swing.JTextField();
        IronAndWashL1 = new javax.swing.JLabel();
        IronandWashTFEdit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        foldTFEdit = new javax.swing.JTextField();
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        aceptEditButton = new javax.swing.JButton();
        cancelEditButton = new javax.swing.JButton();
        topcenterEdit = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        center = new javax.swing.JPanel();
        verPanel = new javax.swing.JPanel();
        topCenter = new javax.swing.JPanel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        editButton = new javax.swing.JButton();
        centerScroll = new javax.swing.JScrollPane();
        schemaClothes = new javax.swing.JTable();
        bot = new javax.swing.JPanel();
        AcceptB = new javax.swing.JButton();
        CancelB = new javax.swing.JButton();
        newArticlePanel = new javax.swing.JPanel();
        chekboxPanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        WashC = new javax.swing.JCheckBox();
        IronC = new javax.swing.JCheckBox();
        WaiC = new javax.swing.JCheckBox();
        foldC = new javax.swing.JCheckBox();
        centerLeftPanel = new javax.swing.JPanel();
        GenderL = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        GenderBox = new javax.swing.JComboBox<>();
        AddGenderB = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        NameL = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        LaundryL = new javax.swing.JLabel();
        WashTF = new javax.swing.JTextField();
        IronL = new javax.swing.JLabel();
        IronTF = new javax.swing.JTextField();
        IronAndWashL = new javax.swing.JLabel();
        IronandWashTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        foldTF = new javax.swing.JTextField();

        genderDialog.setBounds(new java.awt.Rectangle(300, 300, 230, 150));
        genderDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        genderDialog.setResizable(false);
        genderDialog.getContentPane().setLayout(new java.awt.GridBagLayout());

        acceptNewGenderButtonDialog.setText("Aceptar");
        acceptNewGenderButtonDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acceptNewGenderButtonDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptNewGenderButtonDialogActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        genderDialog.getContentPane().add(acceptNewGenderButtonDialog, gridBagConstraints);

        jButton2.setText("Cancelar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        genderDialog.getContentPane().add(jButton2, gridBagConstraints);

        newGenderLabelDialog.setText("Ingrese el nuevo Genero");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        genderDialog.getContentPane().add(newGenderLabelDialog, gridBagConstraints);

        newGenderTFDialog.setText("NewGender");
        newGenderTFDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGenderTFDialogMouseClicked(evt);
            }
        });
        newGenderTFDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGenderTFDialogActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        genderDialog.getContentPane().add(newGenderTFDialog, gridBagConstraints);

        editArticlePanel.setPreferredSize(new java.awt.Dimension(500, 400));
        editArticlePanel.setLayout(new java.awt.BorderLayout());

        chekboxPanelEdit.setLayout(new java.awt.GridLayout(11, 1, 5, 5));
        chekboxPanelEdit.add(filler9);
        chekboxPanelEdit.add(filler10);
        chekboxPanelEdit.add(availableCEdit);
        chekboxPanelEdit.add(filler13);
        chekboxPanelEdit.add(WashCEdit);
        chekboxPanelEdit.add(IronCEdit);
        chekboxPanelEdit.add(WaiCEdit);
        chekboxPanelEdit.add(foldCEdit);

        editArticlePanel.add(chekboxPanelEdit, java.awt.BorderLayout.LINE_END);

        centerLeftPanelEdit.setLayout(new java.awt.GridLayout(11, 2, 5, 5));

        GenderL1.setText("Género:");
        centerLeftPanelEdit.add(GenderL1);
        centerLeftPanelEdit.add(filler15);

        centerLeftPanelEdit.add(GenderBoxEdit);
        centerLeftPanelEdit.add(filler18);

        AvalL1.setText("Disponibilidad:");
        centerLeftPanelEdit.add(AvalL1);
        centerLeftPanelEdit.add(filler16);

        NameL1.setText("Nombre:");
        centerLeftPanelEdit.add(NameL1);

        NameTFEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTFEditActionPerformed(evt);
            }
        });
        centerLeftPanelEdit.add(NameTFEdit);

        LaundryL1.setText("Lavado:");
        centerLeftPanelEdit.add(LaundryL1);

        WashTFEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WashTFEditActionPerformed(evt);
            }
        });
        centerLeftPanelEdit.add(WashTFEdit);

        IronL1.setText("Planchado:");
        centerLeftPanelEdit.add(IronL1);

        IronTFEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IronTFEditActionPerformed(evt);
            }
        });
        centerLeftPanelEdit.add(IronTFEdit);

        IronAndWashL1.setText("Lav. y Plan.:");
        centerLeftPanelEdit.add(IronAndWashL1);
        centerLeftPanelEdit.add(IronandWashTFEdit);

        jLabel2.setText("Doblado:");
        centerLeftPanelEdit.add(jLabel2);

        foldTFEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foldTFEditActionPerformed(evt);
            }
        });
        centerLeftPanelEdit.add(foldTFEdit);
        centerLeftPanelEdit.add(filler17);
        centerLeftPanelEdit.add(filler14);

        aceptEditButton.setText("Aceptar");
        aceptEditButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptEditButtonActionPerformed(evt);
            }
        });
        centerLeftPanelEdit.add(aceptEditButton);

        cancelEditButton.setText("Cancelar");
        cancelEditButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEditButtonActionPerformed(evt);
            }
        });
        centerLeftPanelEdit.add(cancelEditButton);

        editArticlePanel.add(centerLeftPanelEdit, java.awt.BorderLayout.CENTER);

        jLabel3.setText("Editar Articulo");
        topcenterEdit.add(jLabel3);

        editArticlePanel.add(topcenterEdit, java.awt.BorderLayout.NORTH);

        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setLayout(new java.awt.BorderLayout());

        verPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout centerLayout = new javax.swing.GroupLayout(center);
        center.setLayout(centerLayout);
        centerLayout.setHorizontalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        centerLayout.setVerticalGroup(
            centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(verPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(center, java.awt.BorderLayout.PAGE_START);

        topCenter.setLayout(new java.awt.GridLayout(1, 4, 5, 5));
        topCenter.add(filler8);
        topCenter.add(filler11);
        topCenter.add(filler12);

        editButton.setText("Editar");
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        topCenter.add(editButton);

        centerScroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                centerScrollMouseClicked(evt);
            }
        });

        schemaClothes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Género", "Nombre", "Lavado", "Planchado", "Lavado y Planchado", "Doblado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        schemaClothes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        schemaClothes.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        schemaClothes.setMinimumSize(new java.awt.Dimension(0, 0));
        schemaClothes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        schemaClothes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schemaClothesMouseClicked(evt);
            }
        });
        centerScroll.setViewportView(schemaClothes);
        schemaClothes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (schemaClothes.getColumnModel().getColumnCount() > 0) {
            schemaClothes.getColumnModel().getColumn(0).setResizable(false);
            schemaClothes.getColumnModel().getColumn(1).setResizable(false);
            schemaClothes.getColumnModel().getColumn(2).setResizable(false);
            schemaClothes.getColumnModel().getColumn(3).setResizable(false);
            schemaClothes.getColumnModel().getColumn(4).setResizable(false);
            schemaClothes.getColumnModel().getColumn(5).setResizable(false);
        }

        bot.setPreferredSize(new java.awt.Dimension(200, 30));
        bot.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        AcceptB.setText("Aceptar");
        AcceptB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AcceptB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptBActionPerformed(evt);
            }
        });
        bot.add(AcceptB);

        CancelB.setText("Cancelar");
        CancelB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBActionPerformed(evt);
            }
        });
        bot.add(CancelB);

        newArticlePanel.setLayout(new java.awt.BorderLayout());

        chekboxPanel.setLayout(new java.awt.GridLayout(11, 1, 5, 5));
        chekboxPanel.add(filler1);
        chekboxPanel.add(filler5);
        chekboxPanel.add(filler6);
        chekboxPanel.add(filler7);
        chekboxPanel.add(WashC);
        chekboxPanel.add(IronC);
        chekboxPanel.add(WaiC);
        chekboxPanel.add(foldC);

        newArticlePanel.add(chekboxPanel, java.awt.BorderLayout.LINE_END);

        centerLeftPanel.setLayout(new java.awt.GridLayout(11, 2, 5, 5));

        GenderL.setText("Género:");
        centerLeftPanel.add(GenderL);
        centerLeftPanel.add(filler2);

        centerLeftPanel.add(GenderBox);

        AddGenderB.setText("Añadir");
        AddGenderB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddGenderB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGenderBActionPerformed(evt);
            }
        });
        centerLeftPanel.add(AddGenderB);
        centerLeftPanel.add(filler3);
        centerLeftPanel.add(filler4);

        NameL.setText("Nombre:");
        centerLeftPanel.add(NameL);

        NameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTFActionPerformed(evt);
            }
        });
        centerLeftPanel.add(NameTF);

        LaundryL.setText("Lavado:");
        centerLeftPanel.add(LaundryL);

        WashTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WashTFActionPerformed(evt);
            }
        });
        centerLeftPanel.add(WashTF);

        IronL.setText("Planchado:");
        centerLeftPanel.add(IronL);

        IronTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IronTFActionPerformed(evt);
            }
        });
        centerLeftPanel.add(IronTF);

        IronAndWashL.setText("Lav. y Plan.:");
        centerLeftPanel.add(IronAndWashL);
        centerLeftPanel.add(IronandWashTF);

        jLabel1.setText("Doblado:");
        centerLeftPanel.add(jLabel1);

        foldTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foldTFActionPerformed(evt);
            }
        });
        centerLeftPanel.add(foldTF);

        newArticlePanel.add(centerLeftPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newArticlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(topCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(centerScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(topCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(centerScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(623, 623, 623)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newArticlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(bot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddGenderBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGenderBActionPerformed
        genderDialog.setVisible(true);
    }//GEN-LAST:event_AddGenderBActionPerformed

    private void NameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTFActionPerformed

    private void WashTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WashTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WashTFActionPerformed

    private void IronTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IronTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IronTFActionPerformed

    private void foldTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foldTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foldTFActionPerformed

    private void AcceptBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBActionPerformed
/*
        art.setGender((String)GenderBox.getSelectedItem());
        art.setClothName((String)NameTF.getText());
        art.setWashPrice((Float.parseFloat(WashTF.getText())));
        art.setWashA(WashC.isSelected());
        art.setWaiPrice(Float.parseFloat(IronandWashTF.getText()));
        art.setWaiA(WaiC.isSelected());
        art.setIronPrice(Float.parseFloat(IronTF.getText()));
        art.setIronA(IronC.isSelected());
        art.setFoldPrice(Float.parseFloat(foldTF.getText()));
        art.setIronA(foldC.isSelected());

        daoT.update(art);
        TableUtils.fillTable(schemaClothes,daoT.findAll());
        BoxUtils.updateBox(daoT.getGenders(),GenderBox);*/
        //         TODO add your handling code here:
        
        NameTF.setText("");
        WashTF.setText("");
        IronTF.setText("");
        IronandWashTF.setText("");
        foldTF.setText("");
        
        WashC.setSelected(false);
        IronC.setSelected(false);
        WaiC.setSelected(false);
        foldC.setSelected(false);
    }//GEN-LAST:event_AcceptBActionPerformed

    private void schemaClothesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schemaClothesMouseClicked
/*        BoxUtils.updateBox(daoT.getGenders(),GenderBox);
        String a,b;

        a= (String)schemaClothes.getValueAt(schemaClothes.getSelectedRow(), 0);
        b= (String)schemaClothes.getValueAt(schemaClothes.getSelectedRow(), 1);
        art.setGender(a);
        art.setClothName(b);
        art=daoT.read(schemaClothes.getSelectedRow()+1);
        GenderBox.setSelectedItem(art.getGender());
        NameTF.setText(art.getClothName());
        WashTF.setText(Float.toString(art.getWashPrice()));
        WashC.setSelected(art.isWashA());
        IronandWashTF.setText(Float.toString(art.getWaiPrice()));
        WaiC.setSelected(art.isWaiA());
        IronTF.setText(Float.toString(art.getIronPrice()));
        IronC.setSelected(art.isIronA());
        foldTF.setText(Float.toString(art.getFoldPrice()));
        foldC.setSelected(art.isFoldA());
        // TODO add your handling code here:*/
    }//GEN-LAST:event_schemaClothesMouseClicked

    private void centerScrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_centerScrollMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_centerScrollMouseClicked

    private void NameTFEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTFEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTFEditActionPerformed

    private void WashTFEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WashTFEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WashTFEditActionPerformed

    private void IronTFEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IronTFEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IronTFEditActionPerformed

    private void foldTFEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foldTFEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foldTFEditActionPerformed

    private void aceptEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptEditButtonActionPerformed
        
        //PONER ESTO DESPUES DE RECOGER LOS DATOS!!! ESTO LOS BORRA
        NameTFEdit.setText("");
        WashTFEdit.setText("");
        IronTFEdit.setText("");
        IronandWashTFEdit.setText("");
        foldTFEdit.setText("");
        
        availableCEdit.setSelected(false);
        WashCEdit.setSelected(false);
        IronCEdit.setSelected(false);
        WaiCEdit.setSelected(false);
        foldCEdit.setSelected(false);
        
        center.setVisible(false);
        center.removeAll();
        center.setLayout(new BorderLayout());
        center.add(verPanel);
        center.setVisible(true);
    }//GEN-LAST:event_aceptEditButtonActionPerformed

    private void newGenderTFDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGenderTFDialogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newGenderTFDialogActionPerformed

    private void newGenderTFDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGenderTFDialogMouseClicked
        newGenderTFDialog.setText("");
    }//GEN-LAST:event_newGenderTFDialogMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        genderDialog.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void acceptNewGenderButtonDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptNewGenderButtonDialogActionPerformed
        genderDialog.dispose();
    }//GEN-LAST:event_acceptNewGenderButtonDialogActionPerformed

    private void CancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBActionPerformed
        NameTF.setText("");
        WashTF.setText("");
        IronTF.setText("");
        IronandWashTF.setText("");
        foldTF.setText("");
        
        WashC.setSelected(false);
        IronC.setSelected(false);
        WaiC.setSelected(false);
        foldC.setSelected(false);
               
        
    }//GEN-LAST:event_CancelBActionPerformed

    private void cancelEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEditButtonActionPerformed
        NameTFEdit.setText("");
        WashTFEdit.setText("");
        IronTFEdit.setText("");
        IronandWashTFEdit.setText("");
        foldTFEdit.setText("");
        
        availableCEdit.setSelected(false);
        WashCEdit.setSelected(false);
        IronCEdit.setSelected(false);
        WaiCEdit.setSelected(false);
        foldCEdit.setSelected(false);
        
        center.setVisible(false);
        center.removeAll();
        center.setLayout(new BorderLayout());
        center.add(verPanel);
        center.setVisible(true);
    }//GEN-LAST:event_cancelEditButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        center.setVisible(false);
        center.removeAll();
        center.setLayout(new BorderLayout());
        center.add(editArticlePanel);
        center.setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptB;
    private javax.swing.JButton AddGenderB;
    private javax.swing.JLabel AvalL1;
    private javax.swing.JButton CancelB;
    protected static javax.swing.JComboBox<String> GenderBox;
    protected static javax.swing.JComboBox<String> GenderBoxEdit;
    private javax.swing.JLabel GenderL;
    private javax.swing.JLabel GenderL1;
    private javax.swing.JLabel IronAndWashL;
    private javax.swing.JLabel IronAndWashL1;
    private javax.swing.JCheckBox IronC;
    private javax.swing.JCheckBox IronCEdit;
    private javax.swing.JLabel IronL;
    private javax.swing.JLabel IronL1;
    private javax.swing.JTextField IronTF;
    private javax.swing.JTextField IronTFEdit;
    private javax.swing.JTextField IronandWashTF;
    private javax.swing.JTextField IronandWashTFEdit;
    private javax.swing.JLabel LaundryL;
    private javax.swing.JLabel LaundryL1;
    private javax.swing.JLabel NameL;
    private javax.swing.JLabel NameL1;
    private javax.swing.JTextField NameTF;
    private javax.swing.JTextField NameTFEdit;
    private javax.swing.JCheckBox WaiC;
    private javax.swing.JCheckBox WaiCEdit;
    private javax.swing.JCheckBox WashC;
    private javax.swing.JCheckBox WashCEdit;
    private javax.swing.JTextField WashTF;
    private javax.swing.JTextField WashTFEdit;
    private javax.swing.JButton acceptNewGenderButtonDialog;
    private javax.swing.JButton aceptEditButton;
    private javax.swing.JCheckBox availableCEdit;
    private javax.swing.JPanel bot;
    private javax.swing.JButton cancelEditButton;
    private javax.swing.JPanel center;
    private javax.swing.JPanel centerLeftPanel;
    private javax.swing.JPanel centerLeftPanelEdit;
    private javax.swing.JScrollPane centerScroll;
    private javax.swing.JPanel chekboxPanel;
    private javax.swing.JPanel chekboxPanelEdit;
    private javax.swing.JPanel editArticlePanel;
    private javax.swing.JButton editButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JCheckBox foldC;
    private javax.swing.JCheckBox foldCEdit;
    private javax.swing.JTextField foldTF;
    private javax.swing.JTextField foldTFEdit;
    private javax.swing.JDialog genderDialog;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel newArticlePanel;
    private javax.swing.JLabel newGenderLabelDialog;
    private javax.swing.JTextField newGenderTFDialog;
    public static javax.swing.JTable schemaClothes;
    private javax.swing.JPanel topCenter;
    private javax.swing.JPanel topcenterEdit;
    private javax.swing.JPanel verPanel;
    // End of variables declaration//GEN-END:variables
}
