/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.Controller;
import Control.LoginControl;
import Utils.PanelUtils;
import Entidad.User;
import java.awt.BorderLayout;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author leons
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    private final MainFrame main;
    private final Controller controller;

    public Login(MainFrame main, Controller controller) {
        this.main = main;
        initComponents();

        this.controller = controller;

        KeyAdapter ka;
        ka = new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    AcceptB.doClick();
                }
            }
        };
        PassTF.addKeyListener(ka);
        NameTF.addKeyListener(ka);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        LoginL = new javax.swing.JLabel();
        userL = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        passL = new javax.swing.JLabel();
        PassTF = new javax.swing.JPasswordField();
        AcceptB = new javax.swing.JButton();
        ExceptionField = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(255, 255, 255));
        setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        setPreferredSize(new java.awt.Dimension(400, 300));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        setLayout(layout);

        LoginL.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        LoginL.setForeground(new java.awt.Color(51, 51, 255));
        LoginL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frontera/password.png"))); // NOI18N
        LoginL.setText("Login");
        LoginL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LoginL.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(LoginL, gridBagConstraints);

        userL.setForeground(new java.awt.Color(51, 51, 255));
        userL.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        add(userL, gridBagConstraints);

        NameTF.setPreferredSize(new java.awt.Dimension(60, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 111;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(NameTF, gridBagConstraints);

        passL.setForeground(new java.awt.Color(51, 51, 255));
        passL.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weightx = 1.0;
        add(passL, gridBagConstraints);

        PassTF.setPreferredSize(new java.awt.Dimension(60, 28));
        PassTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 111;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(PassTF, gridBagConstraints);

        AcceptB.setBackground(new java.awt.Color(153, 255, 255));
        AcceptB.setText("Aceptar");
        AcceptB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 255, 204), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 255), new java.awt.Color(102, 102, 255)));
        AcceptB.setBorderPainted(false);
        AcceptB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AcceptB.setMaximumSize(new java.awt.Dimension(2000, 22));
        AcceptB.setPreferredSize(new java.awt.Dimension(180, 22));
        AcceptB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptBActionPerformed(evt);
            }
        });
        AcceptB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AcceptBKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(AcceptB, gridBagConstraints);

        ExceptionField.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        ExceptionField.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        add(ExceptionField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBActionPerformed
        User user = new User();
        user.setUserName(NameTF.getText());
        user.setPassword(PassTF.getText());

        String result = ((LoginControl) controller).verifyLogin(user);

        controller.executeCallBack(() -> {
//            
            if (result.equals("Administrador") || result.equals("Encargado de cabina")) {
                MainMenu menu = new MainMenu(result, main);
//                main.getBigPanel().add(main.getMenuPanel());
//                main.getBigPanel().add(main.getMainPanel());
                PanelUtils.change(main.getBigPanel(), menu);
                main.getMainTB().setVisible(true);
                main.getExitB().setVisible(true);
                main.getUserLbl().setText(user.getUserName());
            } else {
                ExceptionField.setText(result);
            }
        });


    }//GEN-LAST:event_AcceptBActionPerformed

    private void PassTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassTFActionPerformed

    private void AcceptBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AcceptBKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcceptBKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptB;
    private javax.swing.JLabel ExceptionField;
    private javax.swing.JLabel LoginL;
    private javax.swing.JTextField NameTF;
    private javax.swing.JPasswordField PassTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel passL;
    private javax.swing.JLabel userL;
    // End of variables declaration//GEN-END:variables
}
