/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.ManageAccount;
import Control.ManageArticle;
import DAO.DAOArticle;
import Entidad.Article;
import Utils.BoxUtils;
import Utils.FormUtils;
import Utils.TableUtils;
import java.awt.BorderLayout;
import javax.swing.JComboBox;
import javax.swing.JTable;



/**
 *
 * @author leoleguizamon
 */
public class ManageArticlePanel extends javax.swing.JPanel implements articleInterface {
    
    /**
     * Creates new form ManageArticlePanel
     */
    AddGender addG;
    DAOArticle daoA ;
    public ManageArticlePanel() {
        daoA = new DAOArticle();
        initComponents();
        TableUtils.fillTableArticle(schemaClothes, daoA.findAll());
        BoxUtils.updateBox(daoA.getGenders(), GenderBox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Container = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        newArticlePanel = new javax.swing.JPanel();
        chekboxPanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        WashC = new javax.swing.JCheckBox();
        IronC = new javax.swing.JCheckBox();
        WaiC = new javax.swing.JCheckBox();
        foldC = new javax.swing.JCheckBox();
        centerLeftPanel = new javax.swing.JPanel();
        GenderL = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        GenderBox = new javax.swing.JComboBox<>();
        AddGenderB = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        NameL = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        LaundryL = new javax.swing.JLabel();
        WashTF = new javax.swing.JTextField();
        IronL = new javax.swing.JLabel();
        IronTF = new javax.swing.JTextField();
        IronAndWashL = new javax.swing.JLabel();
        IronandWashTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        foldTF = new javax.swing.JTextField();
        bot = new javax.swing.JPanel();
        AcceptB = new javax.swing.JButton();
        CancelB = new javax.swing.JButton();
        center = new javax.swing.JPanel();
        verPanel = new javax.swing.JPanel();
        topCenter = new javax.swing.JPanel();
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        editButton = new javax.swing.JButton();
        centerScroll = new javax.swing.JScrollPane();
        schemaClothes = new javax.swing.JTable();
        ExceptionField = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 400));

        Container.setLayout(new java.awt.BorderLayout());

        left.setPreferredSize(new java.awt.Dimension(250, 400));
        left.setLayout(new java.awt.BorderLayout());

        newArticlePanel.setLayout(new java.awt.BorderLayout());

        chekboxPanel.setLayout(new java.awt.GridLayout(11, 1, 5, 5));
        chekboxPanel.add(filler1);
        chekboxPanel.add(filler5);
        chekboxPanel.add(filler6);
        chekboxPanel.add(filler7);
        chekboxPanel.add(WashC);
        chekboxPanel.add(IronC);
        chekboxPanel.add(WaiC);
        chekboxPanel.add(foldC);

        newArticlePanel.add(chekboxPanel, java.awt.BorderLayout.LINE_END);

        centerLeftPanel.setLayout(new java.awt.GridLayout(11, 2, 5, 5));

        GenderL.setText("Género:");
        centerLeftPanel.add(GenderL);
        centerLeftPanel.add(filler2);

        centerLeftPanel.add(GenderBox);

        AddGenderB.setText("Añadir");
        AddGenderB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddGenderB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGenderBActionPerformed(evt);
            }
        });
        centerLeftPanel.add(AddGenderB);
        centerLeftPanel.add(filler3);
        centerLeftPanel.add(filler4);

        NameL.setText("Nombre:");
        centerLeftPanel.add(NameL);

        NameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTFActionPerformed(evt);
            }
        });
        centerLeftPanel.add(NameTF);

        LaundryL.setText("Lavado:");
        centerLeftPanel.add(LaundryL);

        WashTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WashTFActionPerformed(evt);
            }
        });
        centerLeftPanel.add(WashTF);

        IronL.setText("Planchado:");
        centerLeftPanel.add(IronL);

        IronTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IronTFActionPerformed(evt);
            }
        });
        centerLeftPanel.add(IronTF);

        IronAndWashL.setText("Lav. y Plan.:");
        centerLeftPanel.add(IronAndWashL);
        centerLeftPanel.add(IronandWashTF);

        jLabel1.setText("Doblado:");
        centerLeftPanel.add(jLabel1);

        foldTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foldTFActionPerformed(evt);
            }
        });
        centerLeftPanel.add(foldTF);

        newArticlePanel.add(centerLeftPanel, java.awt.BorderLayout.CENTER);

        left.add(newArticlePanel, java.awt.BorderLayout.CENTER);

        bot.setPreferredSize(new java.awt.Dimension(200, 30));
        bot.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        AcceptB.setText("Aceptar");
        AcceptB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AcceptB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptBActionPerformed(evt);
            }
        });
        bot.add(AcceptB);

        CancelB.setText("Cancelar");
        CancelB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBActionPerformed(evt);
            }
        });
        bot.add(CancelB);

        left.add(bot, java.awt.BorderLayout.SOUTH);

        Container.add(left, java.awt.BorderLayout.LINE_START);

        center.setLayout(new java.awt.BorderLayout());

        verPanel.setLayout(new java.awt.BorderLayout());

        topCenter.setLayout(new java.awt.GridLayout(1, 4, 5, 5));
        topCenter.add(filler8);
        topCenter.add(filler11);
        topCenter.add(filler12);

        editButton.setText("Editar");
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        topCenter.add(editButton);

        verPanel.add(topCenter, java.awt.BorderLayout.PAGE_START);

        centerScroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                centerScrollMouseClicked(evt);
            }
        });

        schemaClothes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Género", "Nombre", "Lavado", "Planchado", "Lavado y Planchado", "Doblado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        schemaClothes.setColumnSelectionAllowed(true);
        schemaClothes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        schemaClothes.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        schemaClothes.setMinimumSize(new java.awt.Dimension(0, 0));
        schemaClothes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        schemaClothes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schemaClothesMouseClicked(evt);
            }
        });
        centerScroll.setViewportView(schemaClothes);
        schemaClothes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (schemaClothes.getColumnModel().getColumnCount() > 0) {
            schemaClothes.getColumnModel().getColumn(0).setResizable(false);
            schemaClothes.getColumnModel().getColumn(1).setResizable(false);
            schemaClothes.getColumnModel().getColumn(2).setResizable(false);
            schemaClothes.getColumnModel().getColumn(3).setResizable(false);
            schemaClothes.getColumnModel().getColumn(4).setResizable(false);
            schemaClothes.getColumnModel().getColumn(5).setResizable(false);
        }

        verPanel.add(centerScroll, java.awt.BorderLayout.CENTER);

        center.add(verPanel, java.awt.BorderLayout.CENTER);

        Container.add(center, java.awt.BorderLayout.CENTER);

        ExceptionField.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        ExceptionField.setForeground(new java.awt.Color(255, 0, 0));
        Container.add(ExceptionField, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddGenderBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGenderBActionPerformed
        addG = new AddGender(this,daoA.getGenders());
        addG.setVisible(true);
    }//GEN-LAST:event_AddGenderBActionPerformed

    private void NameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTFActionPerformed

    private void WashTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WashTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WashTFActionPerformed

    private void IronTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IronTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IronTFActionPerformed

    private void foldTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foldTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foldTFActionPerformed

    private void AcceptBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBActionPerformed
        
                  
        String exception = FormUtils.validateField(NameTF, GenderBox, WashTF, IronTF, IronandWashTF, foldTF);
        if (exception.equals("")) {
            ExceptionField.setText(exception);
            ManageArticle.createArticle( GenderBox, NameTF, WashTF, IronandWashTF, IronTF,
                    foldTF, WashC, WaiC, IronC, foldC);
            
            TableUtils.fillTableArticle(schemaClothes, daoA.findAll());
            FormUtils.clearFields(NameTF, GenderBox, WashTF, IronTF, IronandWashTF, foldTF);

        }else{
            ExceptionField.setText(exception);
        }
     
    }//GEN-LAST:event_AcceptBActionPerformed

    private void schemaClothesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schemaClothesMouseClicked
      
        ManageArticle.TableClicked(GenderBox, NameTF, WashTF, IronandWashTF, 
                IronTF, foldTF,WashC, WaiC, IronC, foldC, ExceptionField, schemaClothes);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_schemaClothesMouseClicked

    private void centerScrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_centerScrollMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_centerScrollMouseClicked

    private void CancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBActionPerformed
        NameTF.setText("");
        WashTF.setText("");
        IronTF.setText("");
        IronandWashTF.setText("");
        foldTF.setText("");
        
        WashC.setSelected(false);
        IronC.setSelected(false);
        WaiC.setSelected(false);
        foldC.setSelected(false);
               
        
    }//GEN-LAST:event_CancelBActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        String exception = FormUtils.validateField(NameTF, GenderBox, WashTF, IronTF, IronandWashTF, foldTF);
        if (exception.equals("")) {
            ExceptionField.setText(exception);
            ManageArticle.editArticle(GenderBox, NameTF, WashTF, IronandWashTF, IronTF,
                    foldTF, WashC, WaiC, IronC, foldC);
            
            TableUtils.fillTableArticle(schemaClothes, daoA.findAll());
            FormUtils.clearFields(NameTF, GenderBox, WashTF, IronTF, IronandWashTF, foldTF);

        }else{
            ExceptionField.setText(exception);
            }     
    }//GEN-LAST:event_editButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptB;
    private javax.swing.JButton AddGenderB;
    private javax.swing.JButton CancelB;
    private javax.swing.JPanel Container;
    private javax.swing.JLabel ExceptionField;
    protected static javax.swing.JComboBox<String> GenderBox;
    private javax.swing.JLabel GenderL;
    private javax.swing.JLabel IronAndWashL;
    private javax.swing.JCheckBox IronC;
    private javax.swing.JLabel IronL;
    private javax.swing.JTextField IronTF;
    private javax.swing.JTextField IronandWashTF;
    private javax.swing.JLabel LaundryL;
    private javax.swing.JLabel NameL;
    private javax.swing.JTextField NameTF;
    private javax.swing.JCheckBox WaiC;
    private javax.swing.JCheckBox WashC;
    private javax.swing.JTextField WashTF;
    private javax.swing.JPanel bot;
    private javax.swing.JPanel center;
    private javax.swing.JPanel centerLeftPanel;
    private javax.swing.JScrollPane centerScroll;
    private javax.swing.JPanel chekboxPanel;
    private javax.swing.JButton editButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.JCheckBox foldC;
    private javax.swing.JTextField foldTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel left;
    private javax.swing.JPanel newArticlePanel;
    public static javax.swing.JTable schemaClothes;
    private javax.swing.JPanel topCenter;
    private javax.swing.JPanel verPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public JComboBox getGenderBox() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public JTable getSchemaClothes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
