/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.ManageAccount;
import DAO.DAOUser;
import Entidad.User;
import Utils.FormUtils;
import Utils.PanelUtils;
import Utils.TableUtils;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;

/**
 *
 * @author leoleguizamon
 */
public class ManageAccountPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAccountPanel
     */
    
       
    private DAOUser dao = new DAOUser();
    private User usera = new User();
    private User userb = new User(); 
    private User userc = new User(); 
    public ManageAccountPanel() {
        initComponents();
        TableUtils.fillTableUser(userTable, dao.findAll());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        confirmCreate = new javax.swing.JDialog();
        topDialog = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        centerDialog = new javax.swing.JPanel();
        ContraseñaNUsuarioLabel = new javax.swing.JLabel();
        IDNUsuarioLabel = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        labelNuevoUsuario = new javax.swing.JLabel();
        labelContraseña = new javax.swing.JLabel();
        botDialog = new javax.swing.JPanel();
        AceptarBDialogo = new javax.swing.JButton();
        CancelarBDialogo = new javax.swing.JButton();
        confirmUpdate = new javax.swing.JDialog();
        topDialog1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        centerDialog1 = new javax.swing.JPanel();
        ContraseñaNUsuarioLabel1 = new javax.swing.JLabel();
        IDNUsuarioLabel1 = new javax.swing.JLabel();
        labelID1 = new javax.swing.JLabel();
        labelNuevoUsuario1 = new javax.swing.JLabel();
        labelContraseña1 = new javax.swing.JLabel();
        botDialog1 = new javax.swing.JPanel();
        AceptarBDialogo1 = new javax.swing.JButton();
        CancelarBDialogo1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        nameTF = new javax.swing.JTextField();
        lastNameTF = new javax.swing.JTextField();
        userNameTF = new javax.swing.JTextField();
        countryTF = new javax.swing.JTextField();
        adressTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JTextField();
        adminC = new javax.swing.JCheckBox();
        createB = new javax.swing.JButton();
        editAccountButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        centerMainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();

        confirmCreate.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        confirmCreate.setTitle("Confirmar: Nuevo Usuario");
        confirmCreate.setLocation(new java.awt.Point(0, 0));
        confirmCreate.setResizable(false);
        confirmCreate.setSize(new java.awt.Dimension(440, 240));

        topDialog.setLayout(new java.awt.GridLayout(1, 0));

        jLabel3.setText("Se creará un nuevo usuario, este proceso es irreversible");
        topDialog.add(jLabel3);

        confirmCreate.getContentPane().add(topDialog, java.awt.BorderLayout.NORTH);

        centerDialog.setLayout(new java.awt.GridBagLayout());

        ContraseñaNUsuarioLabel.setText("###################");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        centerDialog.add(ContraseñaNUsuarioLabel, gridBagConstraints);

        IDNUsuarioLabel.setText("###################");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        centerDialog.add(IDNUsuarioLabel, gridBagConstraints);

        labelID.setText("ID del nuevo usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        centerDialog.add(labelID, gridBagConstraints);

        labelNuevoUsuario.setText("¿Crear nuevo usuario?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        centerDialog.add(labelNuevoUsuario, gridBagConstraints);

        labelContraseña.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        centerDialog.add(labelContraseña, gridBagConstraints);

        confirmCreate.getContentPane().add(centerDialog, java.awt.BorderLayout.CENTER);

        botDialog.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        AceptarBDialogo.setText("Aceptar");
        AceptarBDialogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AceptarBDialogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarBDialogoActionPerformed(evt);
            }
        });
        botDialog.add(AceptarBDialogo);

        CancelarBDialogo.setText("Cancelar");
        CancelarBDialogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelarBDialogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBDialogoActionPerformed(evt);
            }
        });
        botDialog.add(CancelarBDialogo);

        confirmCreate.getContentPane().add(botDialog, java.awt.BorderLayout.SOUTH);

        confirmUpdate.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        confirmUpdate.setTitle("Confirmar: Nuevo Usuario");
        confirmUpdate.setLocation(new java.awt.Point(0, 0));
        confirmUpdate.setResizable(false);
        confirmUpdate.setSize(new java.awt.Dimension(440, 240));

        topDialog1.setLayout(new java.awt.GridLayout());

        jLabel4.setText("Se editará el usuario seleccionado, ¿continuar?");
        topDialog1.add(jLabel4);

        confirmUpdate.getContentPane().add(topDialog1, java.awt.BorderLayout.NORTH);

        centerDialog1.setLayout(new java.awt.GridBagLayout());

        ContraseñaNUsuarioLabel1.setText("###################");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        centerDialog1.add(ContraseñaNUsuarioLabel1, gridBagConstraints);

        IDNUsuarioLabel1.setText("###################");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        centerDialog1.add(IDNUsuarioLabel1, gridBagConstraints);

        labelID1.setText("ID del usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        centerDialog1.add(labelID1, gridBagConstraints);

        labelNuevoUsuario1.setText("¿Editar usuario?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        centerDialog1.add(labelNuevoUsuario1, gridBagConstraints);

        labelContraseña1.setText("Contraseña:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        centerDialog1.add(labelContraseña1, gridBagConstraints);

        confirmUpdate.getContentPane().add(centerDialog1, java.awt.BorderLayout.LINE_START);

        botDialog1.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        AceptarBDialogo1.setText("Aceptar");
        AceptarBDialogo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AceptarBDialogo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarBDialogo1ActionPerformed(evt);
            }
        });
        botDialog1.add(AceptarBDialogo1);

        CancelarBDialogo1.setText("Cancelar");
        CancelarBDialogo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelarBDialogo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarBDialogo1ActionPerformed(evt);
            }
        });
        botDialog1.add(CancelarBDialogo1);

        confirmUpdate.getContentPane().add(botDialog1, java.awt.BorderLayout.SOUTH);

        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(900, 500));

        jPanel1.setLayout(new java.awt.BorderLayout());

        leftPanel.setPreferredSize(new java.awt.Dimension(200, 400));
        leftPanel.setLayout(new java.awt.GridLayout(12, 1, 5, 5));
        leftPanel.add(filler1);

        nameTF.setText("Nombre");
        nameTF.setMaximumSize(new java.awt.Dimension(10000, 10000));
        nameTF.setMinimumSize(new java.awt.Dimension(0, 0));
        nameTF.setPreferredSize(new java.awt.Dimension(200, 25));
        nameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTFFocusGained(evt);
            }
        });
        nameTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nameTFMouseClicked(evt);
            }
        });
        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });
        leftPanel.add(nameTF);

        lastNameTF.setText("Apellido");
        lastNameTF.setMaximumSize(new java.awt.Dimension(10000, 10000));
        lastNameTF.setMinimumSize(new java.awt.Dimension(0, 0));
        lastNameTF.setPreferredSize(new java.awt.Dimension(200, 25));
        lastNameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastNameTFFocusGained(evt);
            }
        });
        lastNameTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lastNameTFMouseClicked(evt);
            }
        });
        lastNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTFActionPerformed(evt);
            }
        });
        leftPanel.add(lastNameTF);

        userNameTF.setText("Nombre de Usuario");
        userNameTF.setMaximumSize(new java.awt.Dimension(10000, 10000));
        userNameTF.setMinimumSize(new java.awt.Dimension(0, 0));
        userNameTF.setPreferredSize(new java.awt.Dimension(200, 25));
        userNameTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userNameTFMouseClicked(evt);
            }
        });
        leftPanel.add(userNameTF);

        countryTF.setText("País");
        countryTF.setMaximumSize(new java.awt.Dimension(10000, 10000));
        countryTF.setMinimumSize(new java.awt.Dimension(0, 0));
        countryTF.setPreferredSize(new java.awt.Dimension(200, 25));
        countryTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countryTFMouseClicked(evt);
            }
        });
        leftPanel.add(countryTF);

        adressTF.setText("Dirección");
        adressTF.setMaximumSize(new java.awt.Dimension(10000, 10000));
        adressTF.setMinimumSize(new java.awt.Dimension(0, 0));
        adressTF.setPreferredSize(new java.awt.Dimension(200, 25));
        adressTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adressTFMouseClicked(evt);
            }
        });
        adressTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressTFActionPerformed(evt);
            }
        });
        leftPanel.add(adressTF);

        phoneTF.setText("Telefono");
        phoneTF.setMaximumSize(new java.awt.Dimension(10000, 10000));
        phoneTF.setMinimumSize(new java.awt.Dimension(0, 0));
        phoneTF.setPreferredSize(new java.awt.Dimension(200, 25));
        phoneTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneTFMouseClicked(evt);
            }
        });
        phoneTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTFActionPerformed(evt);
            }
        });
        leftPanel.add(phoneTF);

        passwordTF.setText("Contraseña");
        passwordTF.setMaximumSize(new java.awt.Dimension(10000, 10000));
        passwordTF.setMinimumSize(new java.awt.Dimension(0, 0));
        passwordTF.setPreferredSize(new java.awt.Dimension(200, 25));
        passwordTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordTFMouseClicked(evt);
            }
        });
        passwordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTFActionPerformed(evt);
            }
        });
        passwordTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordTFKeyReleased(evt);
            }
        });
        leftPanel.add(passwordTF);

        adminC.setText("Administrador");
        adminC.setMaximumSize(new java.awt.Dimension(10000, 10000));
        adminC.setMinimumSize(new java.awt.Dimension(0, 0));
        adminC.setPreferredSize(new java.awt.Dimension(200, 25));
        leftPanel.add(adminC);

        createB.setText("Crear");
        createB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createB.setMaximumSize(new java.awt.Dimension(10000, 10000));
        createB.setMinimumSize(new java.awt.Dimension(0, 0));
        createB.setPreferredSize(new java.awt.Dimension(200, 25));
        createB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBActionPerformed(evt);
            }
        });
        createB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                createBKeyReleased(evt);
            }
        });
        leftPanel.add(createB);

        editAccountButton.setText("Editar");
        editAccountButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAccountButtonActionPerformed(evt);
            }
        });
        leftPanel.add(editAccountButton);

        cancelButton.setText("Cancelar");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        leftPanel.add(cancelButton);

        jPanel1.add(leftPanel, java.awt.BorderLayout.LINE_START);

        centerPanel.setLayout(new java.awt.BorderLayout(5, 5));

        topPanel.setPreferredSize(new java.awt.Dimension(500, 30));
        topPanel.setLayout(new java.awt.GridLayout(1, 5, 5, 5));
        centerPanel.add(topPanel, java.awt.BorderLayout.NORTH);

        centerMainPanel.setLayout(new java.awt.GridLayout(1, 0));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Nombre de Usuario", "País", "Dirección", "Teléfono", "Contraseña", "Rol"
            }
        ));
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);
        if (userTable.getColumnModel().getColumnCount() > 0) {
            userTable.getColumnModel().getColumn(0).setResizable(false);
            userTable.getColumnModel().getColumn(1).setResizable(false);
            userTable.getColumnModel().getColumn(2).setResizable(false);
            userTable.getColumnModel().getColumn(3).setResizable(false);
            userTable.getColumnModel().getColumn(4).setResizable(false);
            userTable.getColumnModel().getColumn(5).setResizable(false);
            userTable.getColumnModel().getColumn(6).setResizable(false);
            userTable.getColumnModel().getColumn(7).setResizable(false);
        }

        centerMainPanel.add(jScrollPane1);

        centerPanel.add(centerMainPanel, java.awt.BorderLayout.CENTER);

        jPanel1.add(centerPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTFFocusGained
   
    }//GEN-LAST:event_nameTFFocusGained

    private void nameTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameTFMouseClicked
        nameTF.setText("");
    }//GEN-LAST:event_nameTFMouseClicked

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void lastNameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastNameTFFocusGained
        
    }//GEN-LAST:event_lastNameTFFocusGained

    private void lastNameTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastNameTFMouseClicked
        lastNameTF.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTFMouseClicked

    private void lastNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTFActionPerformed

    private void userNameTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameTFMouseClicked
        userNameTF.setText("");          // TODO add your handling code here:
    }//GEN-LAST:event_userNameTFMouseClicked

    private void countryTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countryTFMouseClicked
        countryTF.setText("");          // TODO add your handling code here:
    }//GEN-LAST:event_countryTFMouseClicked

    private void adressTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adressTFMouseClicked
        adressTF.setText("");
    }//GEN-LAST:event_adressTFMouseClicked

    private void adressTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressTFActionPerformed

    private void phoneTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneTFMouseClicked
        phoneTF.setText("");
    }//GEN-LAST:event_phoneTFMouseClicked

    private void phoneTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTFActionPerformed

    private void passwordTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTFMouseClicked
        passwordTF.setText("");
    }//GEN-LAST:event_passwordTFMouseClicked

    private void passwordTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTFKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTFKeyReleased

    private void createBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBActionPerformed

        confirmCreate.setVisible(true);
        confirmCreate.setLocationRelativeTo(null);
        IDNUsuarioLabel.setText(userNameTF.getText());
        ContraseñaNUsuarioLabel.setText(passwordTF.getText());

    }//GEN-LAST:event_createBActionPerformed

    private void createBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createBKeyReleased
   if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            createBActionPerformed(null);                                   //al presionar enter creando el género presiona aceptar y guarda el dato
        }         // TODO add your handling code here
    }//GEN-LAST:event_createBKeyReleased

    private void AceptarBDialogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarBDialogoActionPerformed

        Control.ManageAccount.createUser(nameTF, lastNameTF, userNameTF, countryTF,
            adressTF, passwordTF, phoneTF, adminC);       
    }//GEN-LAST:event_AceptarBDialogoActionPerformed

    private void CancelarBDialogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBDialogoActionPerformed
        confirmCreate.dispose();                 // TODO add your handling code here:
    }//GEN-LAST:event_CancelarBDialogoActionPerformed

    private void passwordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTFActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        nameTF.setText("Nombre");
        lastNameTF.setText("Apellido");
        userNameTF.setText("Nombre de Usuario");
        countryTF.setText("Pais");
        adressTF.setText("Direccion");
        phoneTF.setText("Telefono");
        passwordTF.setText("Contraseña");
        
        adminC.setSelected(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        ManageAccount.TableClicked(nameTF, lastNameTF, userNameTF, countryTF,
                adressTF, phoneTF, passwordTF, userTable);

        // TODO add your handling code here:
    }//GEN-LAST:event_userTableMouseClicked

    private void editAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAccountButtonActionPerformed
        ManageAccount.updateUser(nameTF, lastNameTF, userNameTF, countryTF,
                adressTF, passwordTF, phoneTF, adminC);  
        TableUtils.fillTableUser(userTable, dao.findAll());
        FormUtils.setFields(nameTF, lastNameTF, userNameTF, countryTF,
                adressTF, passwordTF, phoneTF, adminC);// TODO add your handling code here:
    }//GEN-LAST:event_editAccountButtonActionPerformed

    private void AceptarBDialogo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarBDialogo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AceptarBDialogo1ActionPerformed

    private void CancelarBDialogo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarBDialogo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarBDialogo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AceptarBDialogo;
    private javax.swing.JButton AceptarBDialogo1;
    private javax.swing.JButton CancelarBDialogo;
    private javax.swing.JButton CancelarBDialogo1;
    private javax.swing.JLabel ContraseñaNUsuarioLabel;
    private javax.swing.JLabel ContraseñaNUsuarioLabel1;
    private javax.swing.JLabel IDNUsuarioLabel;
    private javax.swing.JLabel IDNUsuarioLabel1;
    private javax.swing.JCheckBox adminC;
    private javax.swing.JTextField adressTF;
    private javax.swing.JPanel botDialog;
    private javax.swing.JPanel botDialog1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel centerDialog;
    private javax.swing.JPanel centerDialog1;
    private javax.swing.JPanel centerMainPanel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JDialog confirmCreate;
    private javax.swing.JDialog confirmUpdate;
    private javax.swing.JTextField countryTF;
    private javax.swing.JButton createB;
    private javax.swing.JButton editAccountButton;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelContraseña1;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelID1;
    private javax.swing.JLabel labelNuevoUsuario;
    private javax.swing.JLabel labelNuevoUsuario1;
    private javax.swing.JTextField lastNameTF;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField passwordTF;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JPanel topDialog;
    private javax.swing.JPanel topDialog1;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField userNameTF;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
