/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Utils.TableUtils;
import DAO.DAOArticle;
import Entidad.Article;
import Utils.BoxUtils;
import Utils.FormUtils;
import java.awt.event.KeyEvent;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author leons
 */
public class NewArticlePanel extends javax.swing.JPanel implements articleInterface {

    /**
     * Creates new form NewServicePanel
     */
    private AddGender addG;            //instancio las ventanas a las que puede acceder este panel
    private final List<String> genders;
    private DAOArticle daoT;

    public NewArticlePanel() {

        initComponents();

        daoT = new DAOArticle();
        genders = daoT.getGenders();

        TableUtils.fillTableArticle(schemaClothes, daoT.findAll());
        BoxUtils.updateBox(daoT.getGenders(), GenderBox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        WashC = new javax.swing.JCheckBox();
        IronTF = new javax.swing.JTextField();
        IronC = new javax.swing.JCheckBox();
        IronandWashTF = new javax.swing.JTextField();
        AvalL = new javax.swing.JLabel();
        IronAndWashL = new javax.swing.JLabel();
        LaundryL = new javax.swing.JLabel();
        WashTF = new javax.swing.JTextField();
        AddGenderB = new javax.swing.JButton();
        NameTF = new javax.swing.JTextField();
        NameL = new javax.swing.JLabel();
        GenderL = new javax.swing.JLabel();
        GenderBox = new javax.swing.JComboBox<>();
        FoldTF = new javax.swing.JTextField();
        FoldL = new javax.swing.JLabel();
        foldC = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        schemaClothes = new javax.swing.JTable();
        AcceptB = new javax.swing.JButton();
        CancelB = new javax.swing.JButton();
        IronL1 = new javax.swing.JLabel();
        ExceptionField = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setPreferredSize(new java.awt.Dimension(800, 469));
        setLayout(new java.awt.BorderLayout(1, 1));

        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        jPanel1.add(WashC, gridBagConstraints);

        IronTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IronTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 58;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel1.add(IronTF, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        jPanel1.add(IronC, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 58;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel1.add(IronandWashTF, gridBagConstraints);

        AvalL.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        AvalL.setText("Disponibilidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel1.add(AvalL, gridBagConstraints);

        IronAndWashL.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        IronAndWashL.setText("Lavado y planchado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 3;
        jPanel1.add(IronAndWashL, gridBagConstraints);

        LaundryL.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        LaundryL.setText("Lavado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        jPanel1.add(LaundryL, gridBagConstraints);

        WashTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WashTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 58;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel1.add(WashTF, gridBagConstraints);

        AddGenderB.setText("Añadir Género");
        AddGenderB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGenderBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel1.add(AddGenderB, gridBagConstraints);

        NameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel1.add(NameTF, gridBagConstraints);

        NameL.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        NameL.setText("Nombre");
        NameL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 0);
        jPanel1.add(NameL, gridBagConstraints);

        GenderL.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        GenderL.setText("Género");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 0);
        jPanel1.add(GenderL, gridBagConstraints);

        GenderBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel1.add(GenderBox, gridBagConstraints);

        FoldTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoldTFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 58;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 15);
        jPanel1.add(FoldTF, gridBagConstraints);

        FoldL.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        FoldL.setText("Doblado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 3;
        jPanel1.add(FoldL, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 5;
        jPanel1.add(foldC, gridBagConstraints);

        schemaClothes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Género", "Nombre", "Lavado", "Lavado y Planchado", "Planchado", "Doblado"
            }
        ));
        jScrollPane1.setViewportView(schemaClothes);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 725;
        gridBagConstraints.ipady = 171;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(jScrollPane1, gridBagConstraints);

        AcceptB.setText("Aceptar");
        AcceptB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptBActionPerformed(evt);
            }
        });
        AcceptB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AcceptBKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        jPanel1.add(AcceptB, gridBagConstraints);

        CancelB.setText("Cancelar");
        CancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 20;
        jPanel1.add(CancelB, gridBagConstraints);

        IronL1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        IronL1.setText("Planchado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        jPanel1.add(IronL1, gridBagConstraints);

        ExceptionField.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        ExceptionField.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        jPanel1.add(ExceptionField, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void IronTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IronTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IronTFActionPerformed

    private void WashTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WashTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WashTFActionPerformed

    private void AddGenderBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGenderBActionPerformed
        addG = new AddGender(this, genders);
        addG.setVisible(true);                   //visibiliza la ventana de añadir genero
    }//GEN-LAST:event_AddGenderBActionPerformed

    private void GenderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderBoxActionPerformed

    private void NameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTFActionPerformed

    private void CancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBActionPerformed
        FormUtils.clearFields(NameTF, GenderBox, WashTF, IronTF, IronandWashTF, FoldTF);                                       //al cancelar oculta la ventana
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelBActionPerformed

    private void AcceptBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBActionPerformed
        Article temp = new Article();
        String exception = FormUtils.validateField(NameTF, GenderBox, WashTF, IronTF, IronandWashTF, FoldTF);
        if (exception.equals("")) {
            ExceptionField.setText(exception);
            temp.setClothName(NameTF.getText());
            temp.setGender((String)GenderBox.getSelectedItem());
            temp.setWashPrice(Float.parseFloat(WashTF.getText()));
            temp.setWashA(WashC.isSelected());
            temp.setWaiPrice(Float.parseFloat(IronandWashTF.getText()));
            temp.setIronPrice(Float.parseFloat(IronTF.getText()));
            temp.setIronA(IronC.isSelected());
            temp.setFoldPrice(Float.parseFloat(FoldTF.getText()));
            temp.setFoldA(foldC.isSelected());
            temp.setStatus(true);
            daoT.create(temp);
            TableUtils.fillTableArticle(schemaClothes, daoT.findAll());
            FormUtils.clearFields(NameTF, GenderBox, WashTF, IronTF, IronandWashTF, FoldTF);
        }else{
            ExceptionField.setText(exception);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_AcceptBActionPerformed

    private void FoldTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoldTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FoldTFActionPerformed

    private void AcceptBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AcceptBKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            AcceptBActionPerformed(null);                                   //al presionar enter creando el género presiona aceptar y guarda el dato
        }         // TODO add your handling code here:
    }//GEN-LAST:event_AcceptBKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptB;
    private javax.swing.JButton AddGenderB;
    private javax.swing.JLabel AvalL;
    private javax.swing.JButton CancelB;
    private javax.swing.JLabel ExceptionField;
    private javax.swing.JLabel FoldL;
    private javax.swing.JTextField FoldTF;
    private javax.swing.JComboBox<String> GenderBox;
    private javax.swing.JLabel GenderL;
    private javax.swing.JLabel IronAndWashL;
    private javax.swing.JCheckBox IronC;
    private javax.swing.JLabel IronL1;
    private javax.swing.JTextField IronTF;
    private javax.swing.JTextField IronandWashTF;
    private javax.swing.JLabel LaundryL;
    private javax.swing.JLabel NameL;
    private javax.swing.JTextField NameTF;
    private javax.swing.JCheckBox WashC;
    private javax.swing.JTextField WashTF;
    private javax.swing.JCheckBox foldC;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable schemaClothes;
    // End of variables declaration//GEN-END:variables

    @Override
    public JTable getSchemaClothes() {
        return schemaClothes;
    }

    @Override
    public JComboBox<String> getGenderBox() {
        return GenderBox;
    }

}
