/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

/**
 *
 * @author usuario
 */
public class StatisticsPanel extends javax.swing.JPanel {

    /**
     * Creates new form Estadisticas
     */
    public StatisticsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        servicePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ServiceTable = new javax.swing.JTable();
        clothesPanel = new javax.swing.JPanel();
        ClothesTable = new javax.swing.JScrollPane();
        servivcePanel1 = new javax.swing.JTable();
        jDialog1 = new javax.swing.JDialog();
        statisticsMainPanel = new javax.swing.JPanel();
        lastYearButton = new javax.swing.JButton();
        lastWeekButton = new javax.swing.JButton();
        lastMonthButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalServiceLabel = new javax.swing.JLabel();
        totalIronLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totalWashLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        totalIWLabel = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        selectedButtonLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();

        servicePanel.setPreferredSize(new java.awt.Dimension(597, 386));

        ServiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cabina", "Lavado", "Planchado", "Lav. y Plan.", "Express", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ServiceTable);
        if (ServiceTable.getColumnModel().getColumnCount() > 0) {
            ServiceTable.getColumnModel().getColumn(0).setResizable(false);
            ServiceTable.getColumnModel().getColumn(1).setResizable(false);
            ServiceTable.getColumnModel().getColumn(2).setResizable(false);
            ServiceTable.getColumnModel().getColumn(3).setResizable(false);
            ServiceTable.getColumnModel().getColumn(4).setResizable(false);
            ServiceTable.getColumnModel().getColumn(5).setResizable(false);
            ServiceTable.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout servicePanelLayout = new javax.swing.GroupLayout(servicePanel);
        servicePanel.setLayout(servicePanelLayout);
        servicePanelLayout.setHorizontalGroup(
            servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
            .addGroup(servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
        );
        servicePanelLayout.setVerticalGroup(
            servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
            .addGroup(servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
        );

        clothesPanel.setPreferredSize(new java.awt.Dimension(597, 386));

        servivcePanel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cabina", "Lavado", "Planchado", "Lav. y Plan.", "Express", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ClothesTable.setViewportView(servivcePanel1);
        if (servivcePanel1.getColumnModel().getColumnCount() > 0) {
            servivcePanel1.getColumnModel().getColumn(0).setResizable(false);
            servivcePanel1.getColumnModel().getColumn(1).setResizable(false);
            servivcePanel1.getColumnModel().getColumn(2).setResizable(false);
            servivcePanel1.getColumnModel().getColumn(3).setResizable(false);
            servivcePanel1.getColumnModel().getColumn(4).setResizable(false);
            servivcePanel1.getColumnModel().getColumn(5).setResizable(false);
            servivcePanel1.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout clothesPanelLayout = new javax.swing.GroupLayout(clothesPanel);
        clothesPanel.setLayout(clothesPanelLayout);
        clothesPanelLayout.setHorizontalGroup(
            clothesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
            .addGroup(clothesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ClothesTable, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
        );
        clothesPanelLayout.setVerticalGroup(
            clothesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
            .addGroup(clothesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ClothesTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setMaximumSize(new java.awt.Dimension(815, 437));
        setMinimumSize(new java.awt.Dimension(815, 437));
        setPreferredSize(new java.awt.Dimension(815, 437));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statisticsMainPanel.setPreferredSize(new java.awt.Dimension(597, 386));

        javax.swing.GroupLayout statisticsMainPanelLayout = new javax.swing.GroupLayout(statisticsMainPanel);
        statisticsMainPanel.setLayout(statisticsMainPanelLayout);
        statisticsMainPanelLayout.setHorizontalGroup(
            statisticsMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        statisticsMainPanelLayout.setVerticalGroup(
            statisticsMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        add(statisticsMainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 40, -1, -1));

        lastYearButton.setText("Ultimo año");
        lastYearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastYearButtonActionPerformed(evt);
            }
        });
        add(lastYearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 56, 194, -1));

        lastWeekButton.setText("Ultima semana");
        lastWeekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastWeekButtonActionPerformed(evt);
            }
        });
        add(lastWeekButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 114, 194, -1));

        lastMonthButton.setText("Ultimo mes");
        lastMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastMonthButtonActionPerformed(evt);
            }
        });
        add(lastMonthButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 85, 194, -1));

        jLabel1.setText("Total:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 143, -1, -1));

        totalServiceLabel.setText("$ ######");
        add(totalServiceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 163, 182, 30));

        totalIronLabel.setText("$ ######");
        add(totalIronLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 219, 182, 30));

        jLabel4.setText("Total planchado:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 199, -1, -1));

        jLabel5.setText("Total lavado:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 255, -1, -1));

        totalWashLabel.setText("$ ######");
        add(totalWashLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 275, 182, 30));

        jLabel7.setText("Total lavado y planchado:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 311, -1, -1));

        totalIWLabel.setText("$ ######");
        add(totalIWLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 331, 182, 30));

        jButton4.setText("Imprimir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(713, 11, 100, -1));

        jLabel9.setText("Estadisticas:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 15, -1, -1));

        selectedButtonLabel.setText("año/mes/semana");
        add(selectedButtonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 15, -1, -1));

        jLabel2.setText("por solicitud/prendas");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 15, -1, -1));

        jToggleButton1.setText("Solicitud/Prendas");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 194, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void lastYearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastYearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastYearButtonActionPerformed

    private void lastMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastMonthButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastMonthButtonActionPerformed

    private void lastWeekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastWeekButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastWeekButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ClothesTable;
    private javax.swing.JTable ServiceTable;
    private javax.swing.JPanel clothesPanel;
    private javax.swing.JButton jButton4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton lastMonthButton;
    private javax.swing.JButton lastWeekButton;
    private javax.swing.JButton lastYearButton;
    private javax.swing.JLabel selectedButtonLabel;
    private javax.swing.JPanel servicePanel;
    private javax.swing.JTable servivcePanel1;
    private javax.swing.JPanel statisticsMainPanel;
    private javax.swing.JLabel totalIWLabel;
    private javax.swing.JLabel totalIronLabel;
    private javax.swing.JLabel totalServiceLabel;
    private javax.swing.JLabel totalWashLabel;
    // End of variables declaration//GEN-END:variables
}
