/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import Control.ChangePanels;

/**
 *
 * @author leons
 */
public class ArticlePanel extends javax.swing.JPanel {

    /**
     * Creates new form ArticlePanel
     */
    public static NewArticlePanel NServ = new NewArticlePanel();
    public static CreateAccount acc = new CreateAccount();
    public static ViewArticles viewT = new ViewArticles();
    public static EditArticle editT = new EditArticle();
    public ArticlePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ServP = new javax.swing.JPanel();
        TBPanel = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        AddB = new javax.swing.JButton();
        ViewSB = new javax.swing.JButton();
        EditSB = new javax.swing.JButton();
        AccountB = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(860, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ServP.setLayout(new java.awt.BorderLayout());
        add(ServP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 800, 470));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(800, 23));

        AddB.setText("Agregar nuevo servicio");
        AddB.setPreferredSize(new java.awt.Dimension(117, 42));
        AddB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBActionPerformed(evt);
            }
        });
        jToolBar1.add(AddB);

        ViewSB.setText("Ver servicios");
        ViewSB.setFocusable(false);
        ViewSB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ViewSB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ViewSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewSBActionPerformed(evt);
            }
        });
        jToolBar1.add(ViewSB);

        EditSB.setText("Editar servicios");
        EditSB.setFocusable(false);
        EditSB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditSB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        EditSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditSBActionPerformed(evt);
            }
        });
        jToolBar1.add(EditSB);

        AccountB.setText("Gestión cuentas");
        AccountB.setFocusable(false);
        AccountB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AccountB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AccountB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountBActionPerformed(evt);
            }
        });
        jToolBar1.add(AccountB);

        javax.swing.GroupLayout TBPanelLayout = new javax.swing.GroupLayout(TBPanel);
        TBPanel.setLayout(TBPanelLayout);
        TBPanelLayout.setHorizontalGroup(
            TBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        TBPanelLayout.setVerticalGroup(
            TBPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TBPanelLayout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(TBPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void AddBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBActionPerformed
      
        ChangePanels.change(ServP, NServ); 
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBActionPerformed

    private void AccountBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountBActionPerformed
        ChangePanels.change(ServP, acc); 
                                              // TODO add your handling code here:
    }//GEN-LAST:event_AccountBActionPerformed

    private void ViewSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewSBActionPerformed
        ChangePanels.change(ServP, viewT);        // TODO add your handling code here:
    }//GEN-LAST:event_ViewSBActionPerformed

    private void EditSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditSBActionPerformed
        ChangePanels.change(ServP, editT);         // TODO add your handling code here:
    }//GEN-LAST:event_EditSBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountB;
    private javax.swing.JButton AddB;
    private javax.swing.JButton EditSB;
    public static javax.swing.JPanel ServP;
    private javax.swing.JPanel TBPanel;
    private javax.swing.JButton ViewSB;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
