/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;

import DAO.DAOArticle;
import Entidad.Article;
import Entidad.User;
import Utils.TableUtils;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author luaalvarezve
 */
public class EditArticle extends javax.swing.JPanel {

    /**
     * Creates new form EditService
     */
    private DAOArticle daoT = new DAOArticle();
     List<String> list = daoT.getGenders();
     Article art = new Article();
     Article art1 = new Article();
        
        DefaultComboBoxModel model = new DefaultComboBoxModel(list.toArray());
    public EditArticle() {
        initComponents();
       
        
        GenderBox.setModel(model);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foldC = new javax.swing.JCheckBox();
        foldTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        IronL1 = new javax.swing.JLabel();
        IronTF = new javax.swing.JTextField();
        IronC = new javax.swing.JCheckBox();
        WaiC = new javax.swing.JCheckBox();
        IronandWashTF = new javax.swing.JTextField();
        IronAndWashL = new javax.swing.JLabel();
        IronL = new javax.swing.JLabel();
        LaundryL = new javax.swing.JLabel();
        WashTF = new javax.swing.JTextField();
        WashC = new javax.swing.JCheckBox();
        AvalL = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        GenderBox = new javax.swing.JComboBox<>();
        GenderL = new javax.swing.JLabel();
        NameL = new javax.swing.JLabel();
        AddGenderB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        schemaClothes = new javax.swing.JTable();
        AcceptB = new javax.swing.JButton();
        CancelB = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));

        foldTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foldTFActionPerformed(evt);
            }
        });

        jLabel1.setText("Doblado");

        IronL1.setText("Planchado");

        IronTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IronTFActionPerformed(evt);
            }
        });

        IronAndWashL.setText("Lavado y ");

        IronL.setText("Planchado");

        LaundryL.setText("Lavado");

        WashTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WashTFActionPerformed(evt);
            }
        });

        AvalL.setText("Disponibilidad");

        NameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTFActionPerformed(evt);
            }
        });

        GenderBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderBoxActionPerformed(evt);
            }
        });

        GenderL.setText("Género");

        NameL.setText("Nombre");

        AddGenderB.setText("Añadir Género");
        AddGenderB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddGenderBActionPerformed(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        schemaClothes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Género", "Nombre", "Lavado", "Lavado y Planchado", "Planchado", "Doblado"
            }
        ));
        schemaClothes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schemaClothesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(schemaClothes);

        AcceptB.setText("Aceptar");
        AcceptB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptBActionPerformed(evt);
            }
        });

        CancelB.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IronL)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(GenderL))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GenderBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(AddGenderB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(AvalL))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IronL1)
                            .addComponent(IronAndWashL)
                            .addComponent(LaundryL)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WashTF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IronandWashTF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IronTF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foldTF, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(foldC)
                            .addComponent(IronC)
                            .addComponent(WaiC)
                            .addComponent(WashC)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NameL)
                        .addGap(18, 18, 18)
                        .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(AcceptB, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(CancelB)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GenderL)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(GenderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddGenderB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AvalL)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LaundryL)
                                    .addComponent(WashTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(IronAndWashL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IronL))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(WaiC)
                                            .addComponent(IronandWashTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(WashC))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(IronTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(IronL1))
                            .addComponent(IronC))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(foldTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(foldC))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AcceptB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void foldTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foldTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foldTFActionPerformed

    private void IronTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IronTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IronTFActionPerformed

    private void WashTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WashTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WashTFActionPerformed

    private void NameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTFActionPerformed

    private void GenderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderBoxActionPerformed

    private void AddGenderBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddGenderBActionPerformed
        NewArticlePanel.addG.setVisible(true);                   //visibiliza la ventana de añadir genero
        // TODO add your handling code here:
    }//GEN-LAST:event_AddGenderBActionPerformed

    private void AcceptBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptBActionPerformed
        
       art.setGender((String)GenderBox.getSelectedItem());
       art.setClothName((String)NameTF.getText());
       art.setWashPrice((Float.parseFloat(WashTF.getText())));
       art.setWashA(WashC.isSelected());
       art.setWaiPrice(Float.parseFloat(IronandWashTF.getText()));
       art.setWaiA(WaiC.isSelected());
       art.setIronPrice(Float.parseFloat(IronTF.getText()));
       art.setIronA(IronC.isSelected());
       art.setFoldPrice(Float.parseFloat(foldTF.getText()));
       art.setIronA(foldC.isSelected());
       
       daoT.update(art);
        TableUtils.fillTable(schemaClothes);
         GenderBox.setModel(model);;     
        // TODO add your handling code here:
    }//GEN-LAST:event_AcceptBActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void schemaClothesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schemaClothesMouseClicked
        
        String a,b;
               
       a= (String)schemaClothes.getValueAt(schemaClothes.getSelectedRow(), 0);
       b= (String)schemaClothes.getValueAt(schemaClothes.getSelectedRow(), 1);
       art.setGender(a);
       art.setClothName(b);
       art=daoT.read(schemaClothes.getSelectedRow()+1);
       GenderBox.setSelectedItem(art.getGender());
       NameTF.setText(art.getClothName());
       WashTF.setText(Float.toString(art.getWashPrice()));
       WashC.setSelected(art.isWashA());
       IronandWashTF.setText(Float.toString(art.getWaiPrice()));
       WaiC.setSelected(art.isWaiA());
       IronTF.setText(Float.toString(art.getIronPrice()));
       IronC.setSelected(art.isIronA());
       foldTF.setText(Float.toString(art.getFoldPrice()));
       foldC.setSelected(art.isFoldA());  
         GenderBox.setModel(model);;        // TODO add your handling code here:
    }//GEN-LAST:event_schemaClothesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptB;
    private javax.swing.JButton AddGenderB;
    private javax.swing.JLabel AvalL;
    private javax.swing.JButton CancelB;
    public static javax.swing.JComboBox<String> GenderBox;
    private javax.swing.JLabel GenderL;
    private javax.swing.JLabel IronAndWashL;
    private javax.swing.JCheckBox IronC;
    private javax.swing.JLabel IronL;
    private javax.swing.JLabel IronL1;
    private javax.swing.JTextField IronTF;
    private javax.swing.JTextField IronandWashTF;
    private javax.swing.JLabel LaundryL;
    private javax.swing.JLabel NameL;
    private javax.swing.JTextField NameTF;
    private javax.swing.JCheckBox WaiC;
    private javax.swing.JCheckBox WashC;
    private javax.swing.JTextField WashTF;
    private javax.swing.JCheckBox foldC;
    private javax.swing.JTextField foldTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable schemaClothes;
    // End of variables declaration//GEN-END:variables
}
