/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontera;



import Utils.PanelUtils;
import Utils.TableUtils;
import DAO.DAOArticle;
import Entidad.Article;
import Entidad.ArticleRequest;
import Utils.BoxUtils;
import java.awt.event.KeyEvent;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author User
 */
public class NewRequestPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewRequestPanel
     */
    private DAOArticle daoT = new DAOArticle();
    private ArticleRequest artR = new ArticleRequest();
    private Article art = new Article();
    
    public NewRequestPanel() {
        initComponents();
         BoxUtils.updateBox(daoT.getGenders(), GenderBox);
         BoxUtils.updateBox(daoT.getClothName((String)GenderBox.getSelectedItem()), ClothBox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CabinTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        GenderBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        clothL = new javax.swing.JLabel();
        ClothBox = new javax.swing.JComboBox<>();
        AddB = new javax.swing.JButton();
        CancelB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        QuantityTF = new javax.swing.JTextField();
        jCheckBox4 = new javax.swing.JCheckBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Id de cabina");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        add(CabinTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 37, 99, -1));

        jLabel2.setText("Género");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, -1, -1));

        GenderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        GenderBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderBoxActionPerformed(evt);
            }
        });
        add(GenderBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 81, 89, -1));

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Género", "Nombre", "Servicio", "Cantidad", "Doblado", "Express"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        requestTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(requestTable);
        if (requestTable.getColumnModel().getColumnCount() > 0) {
            requestTable.getColumnModel().getColumn(0).setResizable(false);
            requestTable.getColumnModel().getColumn(1).setResizable(false);
            requestTable.getColumnModel().getColumn(2).setResizable(false);
            requestTable.getColumnModel().getColumn(3).setResizable(false);
            requestTable.getColumnModel().getColumn(4).setResizable(false);
            requestTable.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 37, 539, -1));

        jCheckBox1.setText("Lavado");
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 231, -1, -1));

        jCheckBox2.setText("Planchado");
        add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jCheckBox3.setText("Doblado");
        add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        clothL.setText("Prenda");
        add(clothL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 133, -1, -1));

        ClothBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(ClothBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 130, 89, -1));

        AddB.setText("Agregar");
        AddB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBActionPerformed(evt);
            }
        });
        add(AddB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        CancelB.setText("Cancelar");
        add(CancelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        jLabel3.setText("Cantidad");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 183, -1, -1));
        add(QuantityTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 180, 89, -1));

        jCheckBox4.setText("Lavado y planchado");
        add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void GenderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderBoxActionPerformed
        BoxUtils.updateBox(daoT.getClothName((String)GenderBox.getSelectedItem()), ClothBox);        // TODO add your handling code here:
    }//GEN-LAST:event_GenderBoxActionPerformed

    private void AddBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBActionPerformed
        String a =(String) ClothBox.getSelectedItem();
        String b = (String)GenderBox.getSelectedItem();
        art.setClothName(a);
        art.setGender(b);
        int c =daoT.findID(art);
        art=daoT.read(c);        
        artR.setArticle(art);
        artR.setQuantity(Integer.parseInt(QuantityTF.getText()));
        
            // TODO add your handling code here:
    }//GEN-LAST:event_AddBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddB;
    private javax.swing.JTextField CabinTF;
    private javax.swing.JButton CancelB;
    private javax.swing.JComboBox<String> ClothBox;
    private javax.swing.JComboBox<String> GenderBox;
    private javax.swing.JTextField QuantityTF;
    private javax.swing.JLabel clothL;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable requestTable;
    // End of variables declaration//GEN-END:variables
}
